services:
  - type: web
    name: mosdac-chatbot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker src.api.main:app
    envVars:
      - key: PORT
        value: 8000
